name: Build for Netlify
on:
  push:
    branches:
      - master
jobs:
  netlify-build-deploy:
    name: Deploying to netlify-build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 13.x
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: yarn install --frozen-lockfile

      - name: Run deploy script
        run: |
          git config user.name "Olajide A. Hammed" && git config user.email "olajide.a.hammed@gmail.com"
          yarn generate
          yarn deploy
